### ISSUE TITLE
Test results are unfair

### ISSUE THREAD

**Issue by pmlopes** [jkyberneees/es4x-vs-nodejs-benchmarks#1]
All node relates tests are using the max capacity of the hardware while ES4X is being forced to "interpreted" mode which means no JIT is available so performance it degraded.

There's no warm up step so there also no time for the JIT to optimize the code, given the point above it will only benefit V8 as it will optimize the node code but again as es4x is running on interpreted mode it will not.

If there is graalvm installed in the target host (you can see it with):

```
java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-20190523183340.buildslave.jdk8u-src-tar--b03)
OpenJDK 64-Bit GraalVM CE 19.1.0 (build 25.212-b03-jvmci-20-b04, mixed mode)
```

And a fresh `npm install` so all previous artifacts are recomputed `rm -Rf node_modules`. On my laptop I can see:

```
node nativenode.js 
Master 5690 is running
Forking process number 0...
Forking process number 1...
Forking process number 2...
Forking process number 3...
Worker 5697 started...
Worker 5704 started...
Worker 5711 started...
Worker 5718 started...
```

And:

```
wrk -t8 -c20 -d30s http://127.0.0.1:3000/hi
Running 30s test @ http://127.0.0.1:3000/hi
  8 threads and 20 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    10.01ms   40.87ms 505.26ms   94.81%
    Req/Sec     2.58k     2.31k    8.34k    53.93%
  603921 requests in 30.03s, 64.51MB read
  Socket errors: connect 1, read 0, write 0, timeout 0
Requests/sec:  20113.21
Transfer/sec:      2.15MB
```

Same for restana

```
node restana.js 
Master 5243 is running
Forking process number 0...
Forking process number 1...
Forking process number 2...
Forking process number 3...
Worker 5250 started...
Worker 5264 started...
Worker 5271 started...
Worker 5257 started...
```

And

```
wrk -t8 -c20 -d30s http://127.0.0.1:3000/hi
Running 30s test @ http://127.0.0.1:3000/hi
  8 threads and 20 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    11.50ms   44.72ms 508.60ms   94.50%
    Req/Sec     2.36k     2.36k    8.57k    71.70%
  547141 requests in 30.02s, 58.44MB read
  Socket errors: connect 1, read 0, write 0, timeout 0
Requests/sec:  18226.99
Transfer/sec:      1.95MB
```

And finally es4x:

```
./node_modules/.bin/es4x-launcher run es4x.js 
Succeeded in deploying verticle
```

With result

```
wrk -t8 -c20 -d30s http://127.0.0.1:3000/hi
Running 30s test @ http://127.0.0.1:3000/hi
  8 threads and 20 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   449.67us    5.02ms 150.73ms   99.63%
    Req/Sec    10.79k     3.41k   16.43k    67.68%
  2575351 requests in 30.10s, 125.26MB read
  Socket errors: connect 1, read 0, write 0, timeout 0
Requests/sec:  85561.29
Transfer/sec:      4.16MB
```

Just using es4x on graalvm will already beat the previous tests. Performance can be even further improved by adding more instances of the es4x verticle but this is already showing the point that the test is flawed.

The test would be correct if there was a warm up step so all JITs can optimize the code for best performance, the tester and server would be in individual servers and the exact same output is verified (say same headers, etc...)

**Comment by jkyberneees** [comment]
Can you please describe the hardware spec you are using? Those are really low numbers for node.
What version of node are you using?
